### ISSUE TITLE
Xcode 8.1 issue

### ISSUE THREAD

**Issue by daviddelmonte** [dstarsboy/ReplaceColor#1]
I'm not a noob but this is out of my depth, and I don't want to be a bull in a china shop. I'm getting this error:

 'init' is unavailable: use 'withMemoryRebound(to:capacity:_)' to temporarily view memory as another layout-compatible type.

on line129 of the View Controller file.. Any suggestions as best way to resolve it?

Many thanks!

**Comment by daviddelmonte** [comment]
I used the following:

```
let b = cubeData.withUnsafeBufferPointer { Data(buffer: $0) }
	let data = b as NSData
```

**Comment by trav-ma** [comment]
Thanks Dave! I updated the code base. I had no idea it was out of date with 8.1.
